language: node_js
node_js:
- '12'
- '10'
services:
- mysql
before_install:
- openssl aes-256-cbc -K $encrypted_7f5915ae251c_key -iv $encrypted_7f5915ae251c_iv
  -in super_secret.txt.enc -out super_secret.txt -d
- npm install
- mysql -e 'CREATE DATABASE IF NOT EXISTS ec_web_test default character set utf8mb4
  collate utf8mb4_unicode_ci;'
- npm install sequelize-cli -g
before_script:
- sequelize db:migrate
script:
- npm test
deploy:
  provider: heroku
  app: secret-brushlands-82653
  api_key:
    secure: be4f0ef4-f01a-43e7-a514-ad48d433e354
  run:
  - npm install sequelize-cli -g
  - sequelize db:migrate
after_success:
- npm run coveralls
