language: node_js
node_js:
- '12'
services:
- mysql
- redis-server
env:
  global:
  - secure: m58kJC5n+KHwsWI1702lt/yAaX57VeKVRfLe1+hfypuJ7AUF+/0NExac0cRTNvyl46E2hEU3phW+97kOcQ+u258omZswLtqT0ywiDKvXH7u9QoSD77eOqFGPE2KC9/74PsrV5SH9QQ3/rUlTpfXoKvsKH+BBDwR2mQnPGbHFBc0KTfi4PrA/Ig2MvtbQRK/6xtvBP/DyrWTshkZznIOaR7QFfKoc8RktA1LkqfOo8TLlm5ZuaAIoXcVh+pKpHmz4dNJVONCmO4da/byQFVbrf1blU2jeltDc+/GoR08AMjH1PieUs7PB84waUHjtrHGDqLGHWa+NtHNdJ9eXDhJ2rUvPW7L/BMdYdW31wOu5sA6u3RS7ak7vNeAS7Ltgpqceq8SdjHx+uT+esNCR+Y7OSkb+aR2gdtngn6CV7ROenC+IDldVk2oqW3mj6oHZCAF0y9cYhzfewIToLw6HiVkbFbinCUC4ar8+AqT4220bllV0Nyn5lRQxYaZNFmpRmbiBzKSVMMnymYK7nOv3B/FQcNHfyW8ANHFHehVeYldCVRc8ELswYpI6ywj3KB/SePGJH79o/MtA3V/80W3ow06nho+150Qo8CFmcXz7CIAjUyGILyZs8+U59a3CHtYtV1gyDlRzq175N9G9OKYZjsu4J7Ix9NbLGulyIQFHUOyr3VY=
before_install:
- openssl aes-256-cbc -K $encrypted_7f5915ae251c_key -iv $encrypted_7f5915ae251c_iv
  -in super_secret.txt.enc -out super_secret.txt -d
- npm install
- mysql -e 'CREATE DATABASE IF NOT EXISTS ec_web_test default character set utf8mb4
  collate utf8mb4_unicode_ci;'
- npm install sequelize-cli -g
before_script:
- sequelize db:migrate --env test
script:
- npm test
deploy:
  provider: heroku
  app: secret-brushlands-82653
  api_key:
    secure: be4f0ef4-f01a-43e7-a514-ad48d433e354
  run:
  - npm install pm2 -g
after_success:
- npm run coveralls
