language: node_js
node_js:
- '12'
- '10'
services:
- mysql
env:
  global:
    secure: rT2THFI2PVRPptxgy/mOrzpcAizxFfxEHGbz7Phi+2B8pwNUMKvX+3z0CHCKx0PIUC1Is8zsORPbRI/eG3pyeEAEBUSNlQmzQSK87f4fh6GxUMPBcPPTVqYlvKa8UTn2VRNR5KFUWC3SzIqD3uCVCxNomgnvFWZY2ooUPJMRX9xtjoGle3s9si9H6QBIqWUaaVZVv+yFbJ7PAVeu3y3LvJzN6SDDqhcNG2A5TXWJVbBIu5L4hBdTJ0ww65TCk2gMxeh+Z7ag1wAIb+of/lKsGKVq5g8JFKOlmnrkuFpH4Pd2jU6fIw/CpTWvVFnsuC9D7wOIux+qznKdY3qCS3mKecoOQgNDYa5HlipL7MuQ8/FV39vN1OGYzQ8NbbbEiP0ksv4xTeFgPaZqUPmgpUFjQ04p9gHJY7VRpXljge9AJsooOoso1AI2bgHa0k0J3TSSrFDSlLLO4yeBZyh6RBccm5jf2TyBzla9rpBGTQlqa7L73+J6zKRyoKB1f3sWxUiajxbbHVQR7E8FJiIRQMiBWRYD+hHDX3AhPT+m1xE7czU6Z5swfZgxFo235GDuHtG4PMkq9gHUxNDdgsZzILEAKAaxkCy66s95C6IhTRkTcpvLpKRN/6Oszz0X+SnOQv7iDwWdqbkZRvH6NE6wTwsp0ssq8hdSPUlha75w86hcmJ8=
before_install:
- openssl aes-256-cbc -K $encrypted_7f5915ae251c_key -iv $encrypted_7f5915ae251c_iv
  -in super_secret.txt.enc -out super_secret.txt -d
- npm install
- mysql -e 'CREATE DATABASE IF NOT EXISTS ec_web_test default character set utf8mb4
  collate utf8mb4_unicode_ci;'
- npm install sequelize-cli -g
before_script:
- sequelize db:migrate --env test
script:
- npm test
deploy:
  provider: heroku
  app: secret-brushlands-82653
  api_key:
    secure: be4f0ef4-f01a-43e7-a514-ad48d433e354
  run:
  - npm install sequelize-cli -g
  - sequelize db:migrate
after_success:
- npm run coveralls
