language: node_js
node_js:
- '12'
- '10'
services:
- mysql
env:
  secure: V8UA3trvpzVpyAA+s4VB9urQAc0dF4FwGba8P599FNQhUi6JsxxH02rvKhe3YGs+OM21m4SYooCix5XfqkluLYO6cbBrD42Ao7o90Dp7KpbJSiVclHEzRtjjkhTeHuZ7VwqvABVWS3TcxF/EURjrqotDPhJxLN7xJoL6HS90GaOOpcuvmkPfPu62Kx63CXytAnuv+nKmAw/bHUJ+JbV+b9MjyXaLpnCW8ij9fs15LROepfXdUpSTeaawq58oey5TMxIPokYwCUgvS4MTO7Yy3cixl+2VKeRSOrfyUychgjsAaSnFSPRDv8A72h80xo+MU2Z6/uNvb6VVata75tu+vus8cwcaIMb0XFZ+qGDjDwsnyiUUfMPUa8ugr90Asq7Omsbhzc5nAtgxrn8ip/wHcTvA1RPluisMJGSLE/HWByJAz6hlDUovf3SOGcXKxjR7YHdsXTNrKOIE46F19vK4OjGCYajOUov3swzfOVNyP3bOuhMQiG8dNMVo2e3fUuSKyHP8lOFM4bWwraf4RJXKtrk/OL6wyixf7J+iszLD0GeYPtfdspFYRxuZpOw9lXtJTdEdUM9Sj0axoxkQoE7FmiZKVlVzsbKmNv9nSUMh3kaJ2omF+FMuk/Aqg1gOa16ZSH+OEQ3mgleDE5J0AfPzggghij/vZ3cla7vRHJ5Vtd0=
before_install:
- openssl aes-256-cbc -K $encrypted_7f5915ae251c_key -iv $encrypted_7f5915ae251c_iv
  -in super_secret.txt.enc -out super_secret.txt -d
- npm install
- mysql -e 'CREATE DATABASE IF NOT EXISTS ec_web_test default character set utf8mb4
  collate utf8mb4_unicode_ci;'
- npm install sequelize-cli -g
before_script:
- sequelize db:migrate
script:
- npm test
deploy:
  provider: heroku
  app: secret-brushlands-82653
  api_key:
    secure: be4f0ef4-f01a-43e7-a514-ad48d433e354
  run:
  - npm install sequelize-cli -g
  - sequelize db:migrate
after_success:
- npm run coveralls
