language: node_js
node_js:
- '12'
- '10'
services:
- mysql
env:
  secure: QrbDSYxk5DNbLn+MJuClvqa8F9uzi+97lYSCLojeXSPIlEZE9dtEMeduKy+IDbc10dV/6SYesVF6VrCTpAT51Ml+7YiZwPO/5bJ51/J+5CLxgZy2SwkXF3rJx/KECMzGvp7R8A9f6acnyixUs8QfvC+bna0/hkMibWm4mqpSvDKqW7lLF5Sb/2DeS+xIyC2c/BJTXiAExrjxvdC8LQpjLCQVEkuQafjk3y30gvW7uWHOZT3rLvoLiqQ5ggTeU5arpNA2Ny0WG98VwGybIbK1XtTf74V+P5rP8l7QkQQFM5V9dIwC3hYq4cmxUDGMsBzlhR4wYzbEZ0UMI4cao3Lzvu2SCW2ShL1/OxqNLRsoPhikWJRk5PAjHaB9dwtqe2w7E6HQIKwkJ7guKCwVHFbyz2VUQW65/pyj4mKP3muNpSyPEG2SpxRx+rqPrOhh8Lf3anCBJ0zwlgZUal/VWfApnj7DN3vqDtaL0AsKKLv+0cJy+52DXcqHNPTCrPH42Y62Qx4H/Zzf7AP/u4wHD6wRp6o0A98Bi7gfgoH6nNk7As7yS7Hvv0s58qm0oN4DqbuCOTth8zoIjIEYQ2NcGHvFxiq/0qTZYxg3DHoaTvKNU7q0myW6MdaF7+1k2tYua8kHGwlMNgp8NDgKizWfm8ndCnPZQPTmeo/Yem0ltWSjCRU=
before_install:
- openssl aes-256-cbc -K $encrypted_7f5915ae251c_key -iv $encrypted_7f5915ae251c_iv
  -in super_secret.txt.enc -out super_secret.txt -d
- npm install
- mysql -e 'CREATE DATABASE IF NOT EXISTS ec_web_test default character set utf8mb4
  collate utf8mb4_unicode_ci;'
- npm install sequelize-cli -g
before_script:
- sequelize db:migrate
script:
- npm test
deploy:
  provider: heroku
  app: secret-brushlands-82653
  api_key:
    secure: be4f0ef4-f01a-43e7-a514-ad48d433e354
  run:
  - npm install sequelize-cli -g
  - sequelize db:migrate
after_success:
- npm run coveralls
