version: '3.2'

services: 
    web:
        build: ./
        ports: 
            - "3000:3000"
        depends_on: 
            - mysql
        command: /bin/bash -c "npm install && npm run dev"
    mysql:
        image: mysql
        container_name: mysqldatabase
        ports:
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: ec_web
            MYSQL_ROOT_PASSWORD: 12345678
        volumes:
            - ./datadir:/var/lib/mysql