version: '3'

services: 
    mysql:
        image: mysql/mysql-server:5.7.22
        container_name: ecwebserverdb
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_HOST: "0.0.0.0"
            MYSQL_ROOT_PASSWORD: "12345678"
            MYSQL_DATABASE: "ec_web_production"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "12345678"
            MYSQL_LOG_CONSOLE: "true"
        command: --character-set-server=utf8
        restart: always
        volumes:
            - ./datadir:/var/lib/mysql
        networks:
            - core
    web:
        build: .
        container_name: ecwebserverprod
        entrypoint: ["/bin/bash", "./entrypoint.sh"]
        ports: 
            - "3000:3000"
        env_file: .env
        links:
            - mysql
        depends_on: 
            - mysql
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules
        networks: 
            - core

volumes: 
    mysql:

networks: 
    core:
        driver: bridge